### ISSUE TITLE
Authenticating with token

### ISSUE THREAD

**Issue by luisffc** [turbot/steampipe-plugin-dockerhub#3]
@bigdatasourav can't authentication be made only with access tokens instead of user + password + 2FA ?
https://github.com/turbot/steampipe-plugin-dockerhub/blob/36ddc86a7235b6b4ef66fe53876d3885988ca0f6/dockerhub/utils.go#L57

Ref: https://docs.docker.com/docker-hub/access-tokens/#use-an-access-token

**Comment by bigdatasourav** [comment]
@luisffc personal access token can be used instead of the password in Docker CLI. It's an alternative to the password.
However, the [SDK](https://github.com/docker/hub-tool/tree/main/pkg#login) is yet to support it. 
For API calls, you need the [JWT/Bearer token](https://docs.docker.com/docker-hub/api/latest/#tag/authentication), which you can get from the login API.
As for the 2FA, it won't break the authentication as once the client is created using the token, we are caching it, and it will work fine. I have tested the scenario.

**Comment by luisffc** [comment]
I see, thanks for expanding on that
